### ISSUE TITLE
V-73387 Hardcodes Domain to "testdomain.com"

### ISSUE THREAD

**Issue by slipthebit** [mitre/microsoft-windows-server-2016-stig-baseline#40] opened 2021-03-16 18:20 UTC
The `dsquery` command in V-73387.rb has the domain hardcoded to "testdomain.com".
The control should use `forrest` as defined in inspec.yml.
```
 ...
   forrest = attribute('forrest')
   domain_role = command('wmic computersystem get domainrole | Findstr /v DomainRole').stdout.strip
   if domain_role == '4' || domain_role == '5'
     query = command("dsquery * \"cn=Default Query Policy,cn=Query Policies,cn=Directory Service, cn=Windows NT,cn=Services,cn=Configuration,dc=testdomain,dc=com\" -attr LDAPAdminLimits").stdout
   ldap_admin_limits = parse_config(query.gsub(/;/, "\n")).params
...
```

**Comment by aaronlippold** [comment] 2021-03-16 18:43
You are correct - we should be using the input.
--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by slipthebit** [comment] 2021-03-17 14:45
Closed initial PR to clean up branching. Opened PR #45 with isolated code change.

**Comment by karikarshivani** [comment] 2021-08-05 17:05
Duplicate of #43 and addressed by PR #45

**Closed by karikarshivani** 2021-08-05 17:05 UTC
